version: '3.3'

services:
  app:
    image: face_analysis:1.0
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 6000:6000