version: '3.3'
services:
  app:
    image: laguzs/gnosis_recognizer_service:1.0
    build: .
    env_file: ./.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}